name: tp0
services:
  server:
    container_name: server
    image: server:latest
    entrypoint: ["python3", "/server/main.py"]
    environment:
      - PYTHONUNBUFFERED=1
      - AMOUNT_CLIENTS=1
    networks:
      - testing_net
    volumes:
      - ./server/config.ini:/config.ini
  client1:
    container_name: client1
    image: client:latest
    entrypoint: ["/client"]
    restart: no
    environment:
      - CLI_ID=1
      - NOMBRE=nombre1
      - APELLIDO=apellido1
      - DOCUMENTO=40867051
      - NACIMIENTO=1990-01-01
      - NUMERO=123456781
    networks:
      - testing_net
    depends_on:
      - server
    volumes:
      - ./client/config.yaml:/config.yaml
networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
